### ISSUE TITLE
v10 Compatibility

### ISSUE THREAD

**Issue by Doresain** [KayelGee/moar-folders#6]
Hey, love this module, thank you. Looks like with v10 it is set to be archived - looks like they're archiving any packages with a compatibleCoreVersion prior to v9. 

Did some cursory testing on v10 testing 2 with max levels set to 6 and everything *seemed* fine - world loaded, no deprecation warnings or errors in the console, UI behaved okay, no mayhem apparent.

It might be as simple as just updating the manifest with the new v10 fields, if you have a chance.

**Comment by Doresain** [comment]
Threw a PR in for this - not a lot of work saved for you but eh every little bit helps. :)

**Comment by KayelGee** [comment]
Thanks for the PR.
I already had tested this aswell and had no apparent issues like you. 
I hadn't yet looked at the manifest changes but when I put out an update for v10 it won't include the fields for v9 because I always only support the most recent stable version and people who decide to stay on v9 can just use the previous version(it won't automatically update to the v10 version).

**Comment by Doresain** [comment]
Sounds good, you're all over it. Thanks man!
